#
# Makefile for the MXS battery charger driver
#

obj-$(CONFIG_BATTERY_MXS) += mxs-battery-mod.o

#mxs-battery-mod-objs := mxs-battery.o
mxs-battery-mod-objs := batt_sm.o ddi_power_battery.o linux.o fiq.o


